# Usa a imagem oficial do Nginx como base
FROM nginx:latest

# Remove os arquivos padrão de HTML
RUN rm -rf /usr/share/nginx/html/*

# Copia seus arquivos HTML personalizados para o diretório padrão do NGINX
COPY html/ /usr/share/nginx/html

# Expõe a porta padrão do NGINX
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]